
work_dir: ./work_dir/pku-mofo1-ft/xsub/unik_joint
model_saved_name: ./runs/pku-mofo1-ft/pku_cs_unik_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/pku/xsub/train_data_joint.npy
  label_path: ./data/pku/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: True
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/pku/xsub/val_data_joint.npy
  label_path: ./data/pku/xsub/val_label.pkl
  debug: False
  random_choose: False
  window_size: -1

# model
model: model.unik_detection.TAG
model_args:
  #weights: ./weights/weights-posetics.pt
  #weights: 'no'
  num_class: 52
  num_joints: 25
  num_person: 2
  #backbone_fixed: False # True for linear classification
  in_channels: 3
  num_heads: 6
  #tau: 300
  
#optim
weight_decay: 0.0001
base_lr: 0.1 #0.05
step: [30, 40]
optimizer: SGD
# training
device: [0,1]
batch_size: 32
test_batch_size: 4
num_epoch: 100
nesterov: True

