
work_dir: ./work_dir/tsu-mpoa/xsub/unik_joint
model_saved_name: ./runs/tsu-mopa/smarthome_cs_unik_joint
# feeder
feeder: feeders.feeder_det.Feeder_det
train_feeder_args:
  data_path: /data/stars/user/dyang/projects2021/TAG_unik/UNIK/data/tsu-w/xsub/train_data_joint.npy
  label_path: /data/stars/user/dyang/projects2021/TAG_unik/UNIK/data/tsu-w/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /data/stars/user/dyang/projects2021/TAG_unik/UNIK/data/tsu-w/xsub/val_data_joint.npy
  label_path: /data/stars/user/dyang/projects2021/TAG_unik/UNIK/data/tsu-w/xsub/val_label.pkl
  debug: False
  random_choose: False
  window_size: -1

# model
model: model.uniact.UniAction
model_args:
  #weights: ./weights/weights-posetics.pt
  #weights: 'no'
  #weights: 
  task: 'detection'
  num_class: 51
  num_joints: 17
  num_person: 2
  #backbone_fixed: True # True for linear classification
  in_channels: 2
#  num_heads: 3
 # tau: 300
  
#optim
weight_decay: 0.0005 #pdan 0.0005
base_lr: 0.001 #pdan 0.001
step: [30, 40]
optimizer: SGD

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 50
nesterov: True

